[pytest]
testpaths =
    api/tests
    ui/tests

addopts = -v --reruns 2 --reruns-delay 1

markers =
    smoke: core stable tests for CI
    regression: full regression tests
    auth: authentication related tests
    external: tests depending on external public API behavior
    api: API tests
    ui: UI tests
    flaky: unstable tests that need investigation

# logging
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S