[pytest]
testpaths =
    api/tests
    ui/tests

addopts = -v

markers =
    api: API tests
    ui: UI tests
    smoke: Smoke tests
    regression: Regression tests

# logging
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S